MODEL:
  META_ARCHITECTURE: "CondInst"
  MASK_ON: True
  BACKBONE:
    NAME: "build_fcos_resnet_fpn_backbone"
  RESNETS:
    OUT_FEATURES: ["res3", "res4", "res5"]
  FPN:
    IN_FEATURES: ["res3", "res4", "res5"]
  PROPOSAL_GENERATOR:
    NAME: "FCOS"
  FCOS:
    THRESH_WITH_CTR: True
    USE_SCALE: True
  CONDINST:
    MAX_PROPOSALS: 500
DATASETS:
  TRAIN: ("coco_stone_train",)
  TEST: ("coco_stone_train",)
SOLVER:
  # IMS_PER_BATCH: 16
  IMS_PER_BATCH: 4
  BASE_LR: 0.01
  STEPS:  (8000, 10000) #(60000, 80000)
  MAX_ITER:  12000 #90000
INPUT:
  MIN_SIZE_TRAIN: (640, 672, 704, 736, 768, 800)
