
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  META_ARCHITECTURE: "CondInst"
  MASK_ON: True
  BACKBONE:
    NAME: "build_fcos_resnet_fpn_backbone"
  RESNETS:
    OUT_FEATURES: ["res3", "res4", "res5"]
    DEPTH: 50
  FPN:
    IN_FEATURES: ["res3", "res4", "res5"]
    OUT_CHANNELS: 96
  PROPOSAL_GENERATOR:
    NAME: "FCOS"
  FCOS:
    THRESH_WITH_CTR: True
    USE_SCALE: True
    NORM: "BN"
    TOP_LEVELS: 0
    NUM_CLS_CONVS: 2
    NUM_BOX_CONVS: 2
    IN_FEATURES: ["p3", "p4", "p5"]
    FPN_STRIDES: [8, 16, 32] 
    BOX_QUALITY: "iou" 
  CONDINST:
    TOPK_PROPOSALS_PER_IM: 64
DATASETS:
  TRAIN: ("coco_stone_train",)
  TEST: ("coco_2017_val",)
SOLVER:
  IMS_PER_BATCH: 12
  BASE_LR: 0.01
  STEPS: (11900, 14500) #(8000, 10000) #(60000, 80000)
  MAX_ITER: 18000 #12000 #90000
INPUT:
  MAX_SIZE_TRAIN: 640
  MIN_SIZE_TRAIN: (300,330,360,390,420,450,480)
  MAX_SIZE_TEST: 640
  MIN_SIZE_TEST: 480